baseURL = "http://surfeandoelcambio.com"
languageCode = "es-es"
title = "Surfeando el cambio"

[params]
google_analytics_id = "G-VH6EMBMDLR"
google_tag_manager_id = ""

  [params.homepage]
  show_call_box = true
  hide_view_all_services = true

  [params.logo]
  mobile = "images/logo/logo-mobile.svg"
  mobile_height = "36px"
  desktop = "images/logo/LogoSurfersVector.svg"
  desktop_height = "36px"
  alt = "Serif - A Hugo Business Theme"

  [params.homepage_meta_tags]
  meta_description = "Impulsamos el talento de las personas para crear futuros extraordinarios."
  meta_og_title = "Surfeando el cambio"
  meta_og_type = "website"
  meta_og_url = "https://surfenadoelcambio.com"
  meta_og_image = 
  meta_og_description = "Impulsamos el talento de las personas para crear futuros extraordinarios."
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"

  [params.team]
  summary_large_truncate = 120

[[menu.main]]
name = "¿Qué ofrecemos?"
url = "/services/"
weight = 1

[[menu.main]]
name = "Equipo"
url = "/team/"
weight = 2

[[menu.main]]
name = "Manifiesto"
url = "/mindset/"
weight = 3

[[menu.main]]
name = "Sobre nosotros"
url = "/about/"
weight = 4

[[menu.main]]
name = "Contacto"
url = "/contact/"
weight = 5

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contacto"
url = "/contact/"
weight = 2
